FROM python:3.9-slim
LABEL Source="https://github.com/AirportR/FullTclash" \
      Builder="We1eVen"
WORKDIR /app
ENV TZ=Asia/Shanghai
ENV CORE=1
ENV THREAD=4
ENV PROXY=0
RUN apt update && apt install -y --no-install-recommends git && \
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    apt clean && rm -rf /var/lib/apt/lists/*
RUN git clone -b master --single-branch  --depth=1 https://github.com/AirportR/FullTclash.git . && rm -rf .git bin/*.exe && \
    pip install -r requirements.txt
COPY config_amd64.yaml resources/config.yaml
COPY main.sh .
RUN  chmod -R +x .
ENTRYPOINT ["./main.sh"]
